# Generated by Django 2.2.12 on 2022-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
